import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:powersync/powersync.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class SupabaseConnector extends PowerSyncBackendConnector {
  final SupabaseClient supabase;
  final String powerSyncUrl;

  SupabaseConnector({
    required this.supabase,
    required this.powerSyncUrl,
  });

  // Tables where Supabase uses a different primary key column than 'id'.
  // PowerSync always stores 'id' locally, but these tables use a named PK in Supabase.
  static const Map<String, String> _tablePkOverrides = {
    'scan_results': 'scan_id',
    'patient_records': 'user_id',
    'doctor_profiles': 'user_id',
  };

  // Column name remaps: local SQLite column name → Supabase column name.
  // Used when the schema uses different names on each side.
  static const Map<String, Map<String, String>> _columnRemaps = {
    'scan_results': {
      'created_at': 'scan_date', // Supabase scan_results.scan_date is NOT NULL
    },
  };

  // Columns to completely strip before pushing to Supabase.
  // Used when a column is auto-generated by the DB (e.g. DEFAULT NOW()) and is
  // NOT in PostgREST's writable schema cache — sending it causes PGRST204.
  static const Map<String, List<String>> _columnsToStrip = {
    'langchain_chat_histories': ['created_at'], // Supabase auto-generates this
  };

  /// Applies any necessary column remaps for a given table before pushing to Supabase.
  Map<String, dynamic>? _remapColumns(String tableName, Map<String, dynamic>? data) {
    if (data == null) return null;
    var result = Map<String, dynamic>.from(data);

    // 1. Strip auto-generated columns that must not be sent to Supabase
    final strips = _columnsToStrip[tableName];
    if (strips != null) {
      for (final col in strips) {
        result.remove(col);
      }
    }

    // Strip local-only sync_status from all tables
    result.remove('sync_status');

    // 2. Rename any columns that differ between SQLite and Supabase
    final remaps = _columnRemaps[tableName];
    if (remaps != null) {
      for (final entry in remaps.entries) {
        if (result.containsKey(entry.key)) {
          result[entry.value] = result.remove(entry.key); // rename key
        }
      }
    }

    // 2.5 Strip local cache paths from image_url so they don't upload to the cloud
    if (result.containsKey('image_url')) {
      final imageUrl = result['image_url'] as String?;
      if (imageUrl != null && (imageUrl.startsWith('/data/user/') || imageUrl.contains('/cache/') || imageUrl.startsWith('file://') || !imageUrl.startsWith('http'))) {
        result['image_url'] = null; // Don't upload local paths to Supabase
      }
    }

    // 3. Decode stringified JSON columns back to Objects so PostgREST accepts them correctly as JSONB
    if (result.containsKey('metadata') && result['metadata'] is String) {
      try {
        result['metadata'] = jsonDecode(result['metadata'] as String);
      } catch (_) {}
    }

    return result;
  }

  // ==========================================
  // 1. FETCH CREDENTIALS (AUTHORIZE DOWNLOADS)
  // ==========================================
  @override
  Future<PowerSyncCredentials?> fetchCredentials() async {
    // 1. Grab the live Supabase session
    var session = Supabase.instance.client.auth.currentSession;

    // 2. If not logged in, return null (PowerSync will wait)
    if (session == null) return null;

    // 3. If the token is expired (or will expire in the next 60 seconds), refresh it.
    //    PowerSync calls fetchCredentials() periodically — stale tokens cause 401s.
    final expiresAt = session.expiresAt;
    final nowSecs = DateTime.now().millisecondsSinceEpoch ~/ 1000;
    final isExpiredOrExpiringSoon = expiresAt != null && expiresAt - nowSecs < 60;

    if (isExpiredOrExpiringSoon) {
      debugPrint('🔄 JWT expiring soon — refreshing Supabase session...');
      try {
        final refreshed = await Supabase.instance.client.auth.refreshSession();
        session = refreshed.session;
        if (session == null) {
          debugPrint('🔴 Session refresh returned null. User must re-login.');
          return null;
        }
        debugPrint('✅ Supabase session refreshed successfully.');
      } catch (e) {
        debugPrint('🔴 Failed to refresh Supabase session: $e');
        return null; // PowerSync will retry
      }
    }

    // 4. Hand the fresh token to PowerSync
    return PowerSyncCredentials(
      endpoint: powerSyncUrl,
      token: session.accessToken,
      userId: session.user.id,
    );
  }

  // ==========================================
  // 2. UPLOAD DATA (PUSH LOCAL CHANGES TO CLOUD)
  // ==========================================
  @override
  Future<void> uploadData(PowerSyncDatabase database) async {
    // 1. Get the queue of offline actions (inserts, updates, deletes)
    final transaction = await database.getNextCrudTransaction();
    if (transaction == null) return; // Nothing to sync!

    try {
      // 2. Loop through every change the user made locally
      for (var crud in transaction.crud) {
        final table = supabase.from(crud.table);

        // Determine the correct primary key column name for this table in Supabase.
        // Most tables use 'id', but some (e.g. scan_results) use a custom PK.
        final pkColumn = _tablePkOverrides[crud.table] ?? 'id';

        // Remap any columns that have different names in Supabase vs local SQLite.
        final remappedData = _remapColumns(crud.table, crud.opData);

        // 3. Push the change to Supabase based on what type of action it was.
        //
        // Tables that are DOWNLOAD-ONLY (never uploaded by the client):
        //   • langchain_chat_histories — the backend LangGraph agent owns all writes.
        //   • scan_results — the Cloud API owns all writes (api/v1/*/predict sets
        //     storage_path, inference_source, modality, etc. that the client can't
        //     set correctly). The RLS policy will be tightened to SELECT-only once
        //     this change is confirmed live. Offline scans stay local-only until
        //     EdgeOutboxService drains them through the API on reconnect.
        const _downloadOnlyTables = {'langchain_chat_histories', 'scan_results'};
        if (_downloadOnlyTables.contains(crud.table)) {
          continue;
        }

        switch (crud.op) {
          case UpdateType.put:
            final payload = { ...?remappedData };
            if (_tablePkOverrides.containsKey(crud.table)) {
              payload.remove('id');
              await table.upsert(payload, onConflict: _tablePkOverrides[crud.table]!);
            } else {
              payload['id'] = crud.id;
              await table.upsert(payload);
            }
            break;

          case UpdateType.patch:
            final payload = { ...?remappedData };
            if (_tablePkOverrides.containsKey(crud.table)) {
              payload.remove('id');
              final pkValue = crud.id; // PowerSync local id IS the PK value for these tables
              await table.update(payload).eq(_tablePkOverrides[crud.table]!, pkValue);
            } else {
              await table.update(payload).eq('id', crud.id);
            }
            break;

          case UpdateType.delete:
            // DELETE removes the row
            // If the table has an override PK, we might not be able to delete without it,
            // but we fall back to the PowerSync id in case the backend also has it.
            await table.delete().eq(pkColumn, crud.id);
            break;
        }
      }

      // 4. If the cloud accepted all changes, clear them from the local queue
      await transaction.complete();

    } on PostgrestException catch (e) {
      // Log the Postgrest error code for debugging
      debugPrint('🔴 Supabase DB Error [${e.code}]: ${e.message}');
      
      // If the error is unrecoverable (e.g. Foreign Key violation, Unique violation),
      // we must complete the transaction with an error to DISCARD the bad row,
      // otherwise PowerSync will retry it forever and block the sync queue.
      const unrecoverableCodes = [
        '23505', // unique_violation
        '23502', // not_null_violation
        '23503', // foreign_key_violation
        '42703', // undefined_column
        '22P02', // invalid_text_representation
        '22003', // numeric_value_out_of_range
      ];
      
      if (e.code != null && unrecoverableCodes.contains(e.code)) {
        await transaction.complete(); // Completing the transaction drops the bad item from the queue
      } else {
        rethrow;
      }
    } catch (e) {
      // Network error — PowerSync will automatically retry on next connection
      debugPrint('⚠️ Upload failed, will retry: $e');
      rethrow;
    }
  }
}