"""Pydantic models for shared request/response contracts across the Gateway.

This module centralizes all data validation schemas utilized across the gateway,
ensuring consistent contract enforcement for inference data, health monitoring,
patient history, and orchestrated conversational exchanges.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class ExplainabilityInfo(BaseModel):
    """Nested explainability block attached to scan responses and history items.

    Attributes:
        status: The ``xai_status`` column value, verbatim.  One of:
            ``"none"``, ``"generated"``, ``"skipped_edge"``, ``"failed"``.
        url: The authenticated Supabase Storage URL of the primary XAI overlay
            image, or ``None``.  Non-null if and only if ``status == 'generated'``.
        modality: The ``modality`` column value (``'cxr'``, ``'ecg'``, ``'skin'``),
            or ``None`` where the column is null.
    """

    status: str
    url: Optional[str] = None
    modality: Optional[str] = None


class InferenceResponse(BaseModel):
    """Standardized response contract for diagnostic inference results.

    This model encapsulates the output generated by downstream machine learning
    services after processing a medical imaging or diagnostic payload.

    Attributes:
        status: The operational status of the inference execution (e.g., 'success', 'error').
        predicted_class: The highest probability diagnostic classification determined by the model.
        probabilities: A mapping of all evaluated classes to their respective confidence probabilities.
        xai_image: A Base64-encoded representation of the explainable AI (XAI) visual overlay.
    """

    status: str = Field(
        ...,
        description="Status of the inference, e.g. 'success'",
    )
    predicted_class: Optional[str] = Field(
        None,
        description="Most likely diagnostic class",
    )
    probabilities: Optional[Dict[str, float]] = Field(
        None,
        description="Class-level probabilities",
    )
    xai_image: Optional[str] = Field(
        None,
        description="Base64-encoded explainability overlay image",
    )

    model_config = {"extra": "forbid"}


class HealthResponse(BaseModel):
    """Standardized health-check response contract.

    Provides the operational status and metadata of the gateway service,
    utilized by load balancers and orchestrators for system monitoring.

    Attributes:
        status: The overall operational health status of the service.
        version: The current deployment version of the Gateway.
        uptime: The server uptime measured in continuous seconds.
    """

    status: str = Field("healthy", description="Overall service health")
    version: str = Field("0.1.0", description="Gateway version")
    uptime: Optional[float] = Field(None, description="Server uptime in seconds")


class PatientHistoryRequest(BaseModel):
    """Request payload for querying longitudinal patient diagnostic history.

    This contract defines the parameters required to retrieve historical
    diagnostic records for a specific patient from the orchestration layer.

    Attributes:
        patient_id: The unique universal identifier for the patient.
        modalities: An optional list of modality filters to restrict the query.
    """

    patient_id: str = Field(
        ...,
        min_length=1,
        description="Unique patient identifier",
    )
    modalities: Optional[List[str]] = Field(
        None,
        description="List of modalities to filter, e.g. ['CXR','ECG']",
    )

    model_config = {"extra": "forbid"}


class RoleMessage(BaseModel):
    """Data contract representing a single conversational turn in the orchestration chat.

    Attributes:
        role: The origin entity of the message (e.g., 'user', 'assistant', 'system').
        content: The textual content of the message.
    """
    
    role: str = Field(..., description='"user" | "assistant" | "system"')
    content: str = Field(...)


class ChatRequest(BaseModel):
    """Request payload for initiating or continuing a chat orchestration session.

    This model structures the contextual data required by the Agentic AI Orchestrator
    to synthesize diagnostic insights and manage complex multi-step workflows.

    Attributes:
        messages: A chronological sequence of role-based messages.
        patient_id: The unique identifier of the patient under review.
        current_scan_id: The identifier of the specific diagnostic scan in context.
        execution_step: The current logical step in the diagnostic orchestration pipeline.
        multimodal_metadata: A flexible dictionary of additional clinical context.
    """

    messages: List[RoleMessage]
    patient_id: str = Field(default="")
    current_scan_id: str = Field(default="")
    execution_step: str = Field(default="")
    multimodal_metadata: Dict[str, Any] = Field(default_factory=dict)


class ScanSyncResponse(BaseModel):
    """Response contract for a successful edge-inference sync operation.

    Returned by ``POST /api/v1/sync/edge-inference`` when the scan row
    was written to ``scan_results`` for the first time.

    Attributes:
        status: Always ``"synced"`` for a successful first-time insert.
        scan_id: The UUID of the scan, matching the client-generated value
            supplied in the request.
        image_url: The public Supabase Storage URL of the uploaded image.
    """

    status: str = Field("synced", description='Always "synced" on first insert.')
    scan_id: str = Field(..., description="UUID of the persisted scan.")
    image_url: str = Field(..., description="Authenticated URL of the uploaded scan image.")
    storage_path: str = Field(..., description="Object path within the storage bucket.")


class ScanAlreadySyncedResponse(BaseModel):
    """Response contract returned when an edge scan was already synced.

    Returned by ``POST /api/v1/sync/edge-inference`` when the supplied
    ``scan_id`` already exists in ``scan_results`` (idempotent duplicate).
    The mobile client should treat this as a success and clear the local queue.

    Attributes:
        status: Always ``"already_synced"``.
        scan_id: The UUID that conflicted.
    """

    status: str = Field("already_synced", description='Always "already_synced" on conflict.')
    scan_id: str = Field(..., description="UUID that already existed in scan_results.")
    storage_path: str = Field(..., description="Object path within the storage bucket.")





class GenerateReportRequest(BaseModel):
    """Payload for generating a clinical diagnostic report.

    Expects a list of scan identifiers to include in the synthesized document.
    """

    selected_scan_ids: List[str] = Field(
        ...,
        description="A list of unique scan identifiers (UUIDs) to aggregate into the report.",
        min_length=1,
    )
    patient_id: str = Field(..., description="The universal identifier of the target patient.")


class HistoryScanItem(BaseModel):
    """A single diagnostic scan record in the patient's history."""
    scan_id: str
    modality: str
    ai_diagnosis: str
    confidence: Optional[float] = None
    scan_status: int
    scan_date: Optional[datetime] = None
    # xai_status is kept as a bare top-level field for backwards compatibility
    # with existing clients.  New clients should use the nested `explainability`
    # object, which also carries the authenticated URL and modality.
    xai_status: str
    has_image: bool = Field(..., description="True if storage_path IS NOT NULL")
    explainability: ExplainabilityInfo


class HistoryResponse(BaseModel):
    """Paginated scan history response."""
    total_count: int
    items: List[HistoryScanItem]


class TrendTransition(BaseModel):
    """Represents a diagnosis progression between two consecutive scans."""
    from_diagnosis: str
    to_diagnosis: str
    days_between: Optional[int] = None
    confidence_delta: Optional[float] = None
    direction: str


class TrendResponse(BaseModel):
    """Progression of diagnostic results for a specific modality over time."""
    scans: List[HistoryScanItem]
    transitions: List[TrendTransition]


class FusionRequest(BaseModel):
    """Request payload for POST /api/v1/fusion/fuse.

    Attributes:
        selected_scan_ids: Optional list of scan UUIDs (as strings) to fuse.
            When omitted the endpoint auto-selects the most recent scan per
            modality for the authenticated caller.
    """

    selected_scan_ids: Optional[List[str]] = Field(
        None,
        description="UUIDs of the scans to fuse. Omit to auto-select the most recent scan per modality.",
    )


class ModalityRisk(BaseModel):
    """Per-modality breakdown entry in the fusion response.

    Attributes:
        modality: The scan modality (``cxr``, ``ecg``, or ``skin``).
        ai_diagnosis: The stored AI diagnosis label for this scan.
        confidence: The model confidence in [0.0, 1.0].
        status: ``"normal"`` or ``"abnormal"`` per the definitive label sets.
    """

    modality: str
    ai_diagnosis: str
    confidence: float
    status: str


class FusionResponse(BaseModel):
    """Response payload for POST /api/v1/fusion/fuse.

    Attributes:
        overall_risk_score: Clinically weighted aggregate risk in [0.0, 1.0].
        risk_level: ``"LOW"`` / ``"MODERATE"`` / ``"HIGH"`` / ``"CRITICAL"`` when
            ``fusion_performed`` is true; ``null`` otherwise.
        critical_alert: True only when ``fusion_performed`` is true and the
            aggregated score meets the critical threshold (≥ 0.85).
        fusion_performed: True when two or more modalities contributed to the score.
        unscored: Modalities excluded from scoring with a reason string.
        modality_risks: Per-modality breakdown for scored modalities only.
        findings_summary: Human-readable clause-per-modality string, no LLM call.
        message: Present only when no valid scans exist (mirrors the agent tool
            message-style response).
    """

    overall_risk_score: float
    risk_level: Optional[str] = None
    critical_alert: bool
    fusion_performed: bool
    unscored: List[str] = Field(default_factory=list)
    modality_risks: List[ModalityRisk] = Field(default_factory=list)
    findings_summary: str = Field(default="")
    clinical_correlation: Optional[str] = None
    message: Optional[str] = None
