"""Pydantic models for shared request/response contracts across the Gateway.

This module centralizes all data validation schemas utilized across the gateway,
ensuring consistent contract enforcement for inference data, health monitoring,
patient history, and orchestrated conversational exchanges.
"""

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class InferenceResponse(BaseModel):
    """Standardized response contract for diagnostic inference results.

    This model encapsulates the output generated by downstream machine learning
    services after processing a medical imaging or diagnostic payload.

    Attributes:
        status: The operational status of the inference execution (e.g., 'success', 'error').
        predicted_class: The highest probability diagnostic classification determined by the model.
        probabilities: A mapping of all evaluated classes to their respective confidence probabilities.
        xai_image: A Base64-encoded representation of the explainable AI (XAI) visual overlay.
    """

    status: str = Field(
        ...,
        description="Status of the inference, e.g. 'success'",
    )
    predicted_class: Optional[str] = Field(
        None,
        description="Most likely diagnostic class",
    )
    probabilities: Optional[Dict[str, float]] = Field(
        None,
        description="Class-level probabilities",
    )
    xai_image: Optional[str] = Field(
        None,
        description="Base64-encoded explainability overlay image",
    )

    model_config = {"extra": "forbid"}


class HealthResponse(BaseModel):
    """Standardized health-check response contract.

    Provides the operational status and metadata of the gateway service,
    utilized by load balancers and orchestrators for system monitoring.

    Attributes:
        status: The overall operational health status of the service.
        version: The current deployment version of the Gateway.
        uptime: The server uptime measured in continuous seconds.
    """

    status: str = Field("healthy", description="Overall service health")
    version: str = Field("0.1.0", description="Gateway version")
    uptime: Optional[float] = Field(None, description="Server uptime in seconds")


class PatientHistoryRequest(BaseModel):
    """Request payload for querying longitudinal patient diagnostic history.

    This contract defines the parameters required to retrieve historical
    diagnostic records for a specific patient from the orchestration layer.

    Attributes:
        patient_id: The unique universal identifier for the patient.
        modalities: An optional list of modality filters to restrict the query.
    """

    patient_id: str = Field(
        ...,
        min_length=1,
        description="Unique patient identifier",
    )
    modalities: Optional[List[str]] = Field(
        None,
        description="List of modalities to filter, e.g. ['CXR','ECG']",
    )

    model_config = {"extra": "forbid"}


class RoleMessage(BaseModel):
    """Data contract representing a single conversational turn in the orchestration chat.

    Attributes:
        role: The origin entity of the message (e.g., 'user', 'assistant', 'system').
        content: The textual content of the message.
    """
    
    role: str = Field(..., description='"user" | "assistant" | "system"')
    content: str = Field(...)


class ChatRequest(BaseModel):
    """Request payload for initiating or continuing a chat orchestration session.

    This model structures the contextual data required by the Agentic AI Orchestrator
    to synthesize diagnostic insights and manage complex multi-step workflows.

    Attributes:
        messages: A chronological sequence of role-based messages.
        patient_id: The unique identifier of the patient under review.
        current_scan_id: The identifier of the specific diagnostic scan in context.
        execution_step: The current logical step in the diagnostic orchestration pipeline.
        multimodal_metadata: A flexible dictionary of additional clinical context.
    """

    messages: List[RoleMessage]
    patient_id: str = Field(default="")
    current_scan_id: str = Field(default="")
    execution_step: str = Field(default="")
    multimodal_metadata: Dict[str, Any] = Field(default_factory=dict)


class ScanSyncResponse(BaseModel):
    """Response contract for a successful edge-inference sync operation.

    Returned by ``POST /api/v1/sync/edge-inference`` when the scan row
    was written to ``scan_results`` for the first time.

    Attributes:
        status: Always ``"synced"`` for a successful first-time insert.
        scan_id: The UUID of the scan, matching the client-generated value
            supplied in the request.
        image_url: The public Supabase Storage URL of the uploaded image.
    """

    status: str = Field("synced", description='Always "synced" on first insert.')
    scan_id: str = Field(..., description="UUID of the persisted scan.")
    image_url: str = Field(..., description="Public URL of the uploaded scan image.")


class ScanAlreadySyncedResponse(BaseModel):
    """Response contract returned when an edge scan was already synced.

    Returned by ``POST /api/v1/sync/edge-inference`` when the supplied
    ``scan_id`` already exists in ``scan_results`` (idempotent duplicate).
    The mobile client should treat this as a success and clear the local queue.

    Attributes:
        status: Always ``"already_synced"``.
        scan_id: The UUID that conflicted.
    """

    status: str = Field("already_synced", description='Always "already_synced" on conflict.')
    scan_id: str = Field(..., description="UUID that already existed in scan_results.")


class ReferralRequest(BaseModel):
    """Data contract representing a request to generate a referral QR payload.

    Attributes:
        patient_id: The universal identifier of the patient being referred.
        diagnostic_summary: A clinical summary justifying the referral.
    """

    patient_id: str = Field(..., description="Unique patient identifier")
    diagnostic_summary: str = Field(..., description="Clinical summary for referral")


class GenerateReportRequest(BaseModel):
    """Data contract for initiating the generation of a clinical PDF report.

    Attributes:
        patient_id: The universal identifier of the patient.
        selected_scan_ids: A list of scan identifiers to include in the report.
        llm_summary: The synthesized clinical interpretation provided by the orchestration agent.
    """

    patient_id: str = Field(..., description="Unique patient identifier")
    selected_scan_ids: List[str] = Field(..., description="List of scan IDs to include")
    llm_summary: str = Field(..., description="LLM-generated clinical summary")
