"""
Pydantic validation contracts defining the API boundary.
These Data Transfer Objects (DTOs) map precisely to the PostgreSQL schemas.
"""
from pydantic import BaseMode, Field, UUID4, ConfigDict
from typing import Optional, Dict, Any
from datetime import datetime
from enum import IntEnum

class ScanModality(IntEnum):
    """
    Enumeration representing the supported diagnostic modalities. 
    """
    ECG = 0
    CXR = 1
    SKIN = 2
    
class DiagnosticRisk(IntEnum):
    """
    Enumeration representing the clinical severity of the inference output.
    """
    NORMAL = 0
    WARNING = 1
    HIGH_RISK = 2
    
class ScanResultPayload(BaseModel):
    """
    Data Transfer Object (DTO) for incoming scan records synchronized from the edge.
    
    This model acts as an impenetrable shield, strictly validating data triggered
    by Supabase Webhooks before allowing it into the LangChain/RAG orchestration layer.
    """
    scan_id: UUID4 = Field(
        ..., 
        description="The cryptographic UUID of the specific scan event."
    )
    user_id: UUID4 = Field(
        ...,
        description="The UUID mapping to patient_records table."
    )
    doctor_id: Optional[UUID4] = Field(
        ...,
        description="The UUID of the attending physician who captured the scan."
    )
    
    scan_type: ScanModality = Field(
        ...,
        description="The physical modality of the diagnostic test."
    )
    scan_status: DiagnosticRisk = Field(
        ...,
        description="The clinical severity classification derived from edge inference."
    )
    
    image_url: Optional[str] = Field(
        ...,
        description="The URL mapping to the raw asset in the Supabase Storage bucket."
    )
    ai_diagnosis: Optional[str] = Field(
        None,
        max_length=255,
        description="The primary classification string generated by the edge model."
    )
    findings: Optional[str] = Field(
        None,
        description="Detailed, raw text findings extracted from the inference output."
    )
    confidence: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="The probabilistic certainty of the edge model's prediction."
    )
    
    metadata: Optional[Dict[str, Any]] = Field(
        default_factory=dict,
        description="An extensible JSON blob for future hardware sensor data."
    )
    scan_data: datetime = Field(
        ...,
        description="The precise ISO 8601 timestamp of data acquisition at the edge."
    )
    
    # Enables the model to read data from ORM objects if necessary
    model_config = ConfigDict(from_attributes=True)
    
    def __repr__(self) -> str:
        """
        Dunder method providing a developer-friendly representation of the instance.

        Returns:
            str: The semantic representation of the payload state.
        """
        return (f"<ScanPayload ID: {self.scan_id} | Modality : {self.scan_type.name} | "
                f"Risk: {self.scan_status.name}>")