"""Report generation service for clinical PDF summaries with QR codes.

This module orchestrates the synthesis of structured clinical PDF reports,
integrating diagnostic metadata, LLM-generated summaries, and securely
signed access URLs encoded as QR codes.
"""

from __future__ import annotations

import hashlib
import io
import os
from typing import Optional, Tuple, List, Dict, Any

import qrcode
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage
from supabase import create_client, Client


class ReportGenerator:
    """Service orchestrating the generation of comprehensive clinical PDF reports.

    This service synthesizes diagnostic findings, machine learning classification
    metadata, and LLM-generated clinical summaries into a standardized PDF format.
    It additionally manages secure cloud storage and the generation of embedded
    QR codes for seamless report access.
    """

    # The Supabase client is created on first use so side‑effects are avoided during
    # import time (the storage service may not be needed in every deployment).
    _supabase: Optional[Client] = None

    @classmethod
    def _get_supabase_client(cls) -> Client:
        """Retrieves or initializes the singleton Supabase client instance.

        Initializes the client using gateway configuration parameters if it has
        not been previously instantiated, ensuring lazy loading of cloud resources.

        Returns:
            Client: An authenticated Supabase client instance.

        Raises:
            RuntimeError: If mandatory configuration variables (supabase_url,
                supabase_service_role_key) are not defined in the environment.
        """
        if cls._supabase is None:
            from app.core.config import gateway_config
            url: str = gateway_config.supabase_url
            key: str = gateway_config.supabase_service_role_key
            if not url or not key:
                raise RuntimeError("supabase_url and supabase_service_role_key must be set in config")
            cls._supabase = create_client(url, key)
        return cls._supabase

    def _build_pdf_story(
        self,
        patient_id: str,
        scan_metadata: List[Dict[str, Any]],
        llm_summary: str,
        qr_img: Optional[Any] = None,
    ) -> bytes:
        """Constructs the PDF document layout and renders it to a byte stream.

        Assembles the clinical report using ReportLab platypus elements,
        structuring the document with standard margins, typographically distinct
        headings, organized metadata sections, and optional embedded imagery.

        Args:
            patient_id (str): The unique identifier assigned to the patient.
            scan_metadata (List[Dict[str, Any]]): A collection of dictionaries containing
                metadata for the relevant diagnostic scans (e.g., modality, class).
            llm_summary (str): The synthesized clinical summary generated by the LLM.
            qr_img (Optional[Any], optional): A PIL Image object representing the
                access QR code to be embedded in the report. Defaults to None.

        Returns:
            bytes: The fully rendered PDF document as a byte array.
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72,
        )
        styles = getSampleStyleSheet()
        title_style = styles["Title"]
        body_style = styles["BodyText"]
        story = []

        story.append(Paragraph("MediScanX Clinical Report", title_style))
        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph(f"Patient ID: {patient_id}", body_style))
        story.append(Spacer(1, 0.1 * inch))

        # --- Scan metadata section ------------------------------------------------
        story.append(Paragraph("Selected Scans:", body_style))
        story.append(Spacer(1, 0.1 * inch))
        for m in scan_metadata:
            scan_text = (
                f"Scan {m.get('id','?')}: modality={m.get('modality','N/A')}, "
                f"predicted class={m.get('class','N/A')}, "
                f"timestamp={m.get('timestamp','N/A')}"
            )
            story.append(Paragraph(scan_text, body_style))
            story.append(Spacer(1, 0.05 * inch))

        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph("LLM Summary:", body_style))
        story.append(Spacer(1, 0.1 * inch))
        story.append(Paragraph(llm_summary, body_style))
        story.append(Spacer(1, 0.2 * inch))

        # QR code (if provided)
        if qr_img is not None:
            qr_buffer = io.BytesIO()
            # qr_img is a PIL Image; convert to PNG bytes in memory
            qr_img.save(qr_buffer, format="PNG")
            qr_buffer.seek(0)
            rl_image = RLImage(qr_buffer, width=2 * inch, height=2 * inch)
            story.append(rl_image)
            story.append(Spacer(1, 0.1 * inch))
            story.append(Paragraph("Scan the QR code to access the report online", body_style))

        doc.build(story)
        return buffer.getvalue()

    def generate_qr_report(
        self,
        patient_id: str,
        scan_metadata: List[Dict[str, Any]],
        llm_summary: str,
    ) -> Tuple[bytes, str, str]:
        """Generates a complete clinical PDF report with cloud storage integration.

        This orchestration method produces a preliminary PDF, secures a cloud storage
        location, generates a signed access URL, embeds this URL as a QR code within
        the final PDF, and finalizes the cloud storage upload.

        Args:
            patient_id (str): The unique identifier assigned to the patient.
            scan_metadata (List[Dict[str, Any]]): A collection of dictionaries detailing
                the specific diagnostic scans to be included in the report.
            llm_summary (str): The clinical interpretation summary synthesized by the LLM.

        Returns:
            Tuple[bytes, str, str]: A tuple containing:
                - The raw bytes of the final generated PDF report.
                - The secure, signed URL providing temporary access to the report.
                - The storage path identifier within the cloud bucket.

        Raises:
            RuntimeError: If the cloud storage provider fails to generate a signed access URL.
        """
        supabase: Client = self._get_supabase_client()
        bucket = supabase.storage.from_("medical_reports")

        # 1. Stage PDF without QR (so we can generate a hash and a signed URL)
        stage_pdf = self._build_pdf_story(patient_id, scan_metadata, llm_summary)
        pdf_hash = hashlib.sha256(stage_pdf).hexdigest()[:16]
        storage_path = f"{patient_id}_{pdf_hash}_report.pdf"

        bucket.upload(
            path=storage_path,
            file=stage_pdf,
            file_options={"content-type": "application/pdf"},
        )

        # 2. Obtain a signed URL pointing to the (still placeholder) object
        signed_resp = bucket.create_signed_url(storage_path, 60 * 60 * 24)  # 24 hours
        signed_url = signed_resp.get("signedURL") or signed_resp.get("signedUrl")
        if not signed_url:
            raise RuntimeError("Could not create signed URL from Supabase")

        # 3. Build the final QR image encoding the signed URL
        qr = qrcode.QRCode(version=1, box_size=10, border=4)
        qr.add_data(signed_url)
        qr.make(fit=True)
        qr_img = qr.make_image(fill_color="black", back_color="white")

        # 4. Build the final PDF that includes the QR image
        final_pdf = self._build_pdf_story(patient_id, scan_metadata, llm_summary, qr_img=qr_img)

        # 5. Replace the placeholder object with the final PDF
        bucket.remove([storage_path])
        bucket.upload(
            path=storage_path,
            file=final_pdf,
            file_options={"content-type": "application/pdf"},
        )

        return final_pdf, signed_url, storage_path
