-- ==============================================================================
-- MediScanX - Unified Baseline Migration (V2)
-- File: 0007_updated_schema.sql
-- Description: Squashes migrations 0001 through 0006 into a single baseline schema.
-- ==============================================================================

BEGIN;


CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

DROP TABLE IF EXISTS chat_sessions CASCADE;
DROP TABLE IF EXISTS langchain_chat_histories CASCADE;
DROP TABLE IF EXISTS medical_documents CASCADE;


CREATE TABLE IF NOT EXISTS doctor_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    specialization TEXT,
    current_hospital TEXT,
    license_number TEXT,
    biography TEXT,
    gender TEXT,
    username TEXT,
    phone_number TEXT,
    location TEXT,
    sync_status TEXT,
    date_of_birth TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS patient_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT,
    phone_number TEXT,
    gender TEXT,
    age INT,
    location TEXT,
    medical_history JSONB DEFAULT '{}'::jsonb,
    username TEXT,
    sync_status TEXT,
    date_of_birth TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS scan_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    scan_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    doctor_id UUID,
    scan_type INT NOT NULL,
    scan_status INT NOT NULL,
    image_url TEXT,
    ai_diagnosis TEXT,
    findings TEXT,
    confidence REAL,
    metadata JSONB DEFAULT '{}'::jsonb,
    scan_date TIMESTAMPTZ NOT NULL,
    vector_embedding vector(768),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Knowledge base for Retrieval-Augmented Generation
CREATE TABLE IF NOT EXISTS rag_corpus (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    content TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    embedding halfvec(768),
    title TEXT,
    source TEXT NOT NULL DEFAULT 'PubMedQA',
    external_id TEXT NOT NULL DEFAULT '',
    specialty_tag TEXT DEFAULT 'thoracic',
    CONSTRAINT uq_rag_corpus_source_external_id UNIQUE (source, external_id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id UUID PRIMARY KEY,
    thread_id UUID NOT NULL,
    patient_id UUID NOT NULL,
    is_user BOOLEAN NOT NULL,
    text TEXT NOT NULL,
    citations JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS checkpoints (
    thread_id TEXT NOT NULL,
    checkpoint_ns TEXT NOT NULL DEFAULT '',
    checkpoint_id TEXT NOT NULL,
    parent_checkpoint_id TEXT,
    type TEXT,
    checkpoint JSONB NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}',
    PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id)
);

CREATE TABLE IF NOT EXISTS checkpoint_blobs (
    thread_id TEXT NOT NULL,
    checkpoint_ns TEXT NOT NULL DEFAULT '',
    channel TEXT NOT NULL,
    version TEXT NOT NULL,
    type TEXT NOT NULL,
    blob BYTEA,
    PRIMARY KEY (thread_id, checkpoint_ns, channel, version)
);

CREATE TABLE IF NOT EXISTS checkpoint_writes (
    thread_id TEXT NOT NULL,
    checkpoint_ns TEXT NOT NULL DEFAULT '',
    checkpoint_id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    idx INTEGER NOT NULL,
    channel TEXT NOT NULL,
    type TEXT,
    blob BYTEA NOT NULL,
    PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id, task_id, idx)
);

CREATE TABLE IF NOT EXISTS checkpoint_migrations (
    v INTEGER PRIMARY KEY
);



CREATE INDEX IF NOT EXISTS idx_rag_corpus_embedding 
    ON rag_corpus USING hnsw (embedding halfvec_cosine_ops);

CREATE INDEX IF NOT EXISTS idx_chat_messages_thread_id ON chat_messages(thread_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_patient_id ON chat_messages(patient_id);



ALTER TABLE doctor_profiles
    DROP CONSTRAINT IF EXISTS fk_doctor_auth,
    ADD CONSTRAINT fk_doctor_auth 
    FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE patient_records
    DROP CONSTRAINT IF EXISTS fk_patient_auth,
    ADD CONSTRAINT fk_patient_auth 
    FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE scan_results
    DROP CONSTRAINT IF EXISTS fk_scan_patient,
    ADD CONSTRAINT fk_scan_patient 
    FOREIGN KEY (user_id) REFERENCES patient_records(user_id) ON DELETE CASCADE;

ALTER TABLE scan_results
    DROP CONSTRAINT IF EXISTS fk_scan_doctor,
    ADD CONSTRAINT fk_scan_doctor 
    FOREIGN KEY (doctor_id) REFERENCES doctor_profiles(user_id) ON DELETE SET NULL;



CREATE OR REPLACE FUNCTION match_rag_corpus (
    query_embedding halfvec(768),
    match_threshold float,
    match_count int,
    filter_source text DEFAULT NULL,
    filter_specialty text DEFAULT NULL
)
RETURNS TABLE (
    id uuid,
    content text,
    metadata jsonb,
    title text,
    source text,
    external_id text,
    similarity float
)
LANGUAGE sql STABLE
AS $$
    SELECT
        rag_corpus.id,
        rag_corpus.content,
        rag_corpus.metadata,
        rag_corpus.title,
        rag_corpus.source,
        rag_corpus.external_id,
        1 - (rag_corpus.embedding <=> query_embedding) AS similarity
    FROM rag_corpus
    WHERE 1 - (rag_corpus.embedding <=> query_embedding) > match_threshold
      AND (filter_source IS NULL OR source = filter_source)
      AND (filter_specialty IS NULL OR specialty_tag = filter_specialty)
    ORDER BY similarity DESC
    LIMIT match_count;
$$;

CREATE OR REPLACE FUNCTION public.handle_new_user_profile()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF (new.raw_user_meta_data->>'role' = 'Doctor') THEN
        INSERT INTO public.doctor_profiles (
            user_id, email, full_name, username, specialization, 
            current_hospital, license_number, biography, gender, 
            phone_number, location, date_of_birth
        )
        VALUES(
            new.id, new.email, new.raw_user_meta_data->>'full_name',
            new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'specialization',
            new.raw_user_meta_data->>'current_hospital', new.raw_user_meta_data->>'license_number',
            new.raw_user_meta_data->>'biography', new.raw_user_meta_data->>'gender',
            new.raw_user_meta_data->>'phone_number', new.raw_user_meta_data->>'location',
            new.raw_user_meta_data->>'date_of_birth'
        );
    ELSE
        INSERT INTO public.patient_records (
            user_id, email, full_name, username, gender, 
            age, phone_number, location, date_of_birth
        )
        VALUES(
            new.id, new.email, new.raw_user_meta_data->>'full_name',
            new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'gender',
            (new.raw_user_meta_data->>'age')::integer, new.raw_user_meta_data->>'phone_number',
            new.raw_user_meta_data->>'location', new.raw_user_meta_data->>'date_of_birth'
        );
    END IF;
    RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_profile();



ALTER TABLE doctor_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE patient_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE scan_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE rag_corpus ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Doctors access own profile" ON doctor_profiles
    FOR ALL USING (user_id = auth.uid());

CREATE POLICY "Doctors access hospital patients" ON patient_records
    FOR ALL USING (
        location = (SELECT current_hospital FROM doctor_profiles WHERE user_id = auth.uid())
    );

CREATE POLICY "Doctors access patient scans" ON scan_results
    FOR ALL USING (
        doctor_id = auth.uid() OR 
        user_id IN (
            SELECT user_id FROM patient_records 
            WHERE location = (SELECT current_hospital FROM doctor_profiles WHERE user_id = auth.uid())
        )
    );

CREATE POLICY "Public read access to RAG corpus" ON rag_corpus
    FOR SELECT TO public USING (true);



DROP PUBLICATION IF EXISTS powersync;
CREATE PUBLICATION powersync FOR TABLE doctor_profiles, patient_records, scan_results, chat_messages;

ALTER TABLE doctor_profiles REPLICA IDENTITY FULL;
ALTER TABLE patient_records REPLICA IDENTITY FULL;
ALTER TABLE scan_results REPLICA IDENTITY FULL;
ALTER TABLE chat_messages REPLICA IDENTITY FULL;

COMMIT;
