"""ECG Optical Digitizer Package — Modularized pipeline inside engine module."""

from .contracts import (
    DigitizationContract,
    DigitizationFailure,
    EvaluationThresholds,
    GridDetectionConfig,
    GridGeometry,
    GridSuppressionResult,
    ImageStandardizationConfig,
    StandardizedECGImage,
    LEAD_NAME_ALIASES,
    LEAD_ORDER,
    REQUIRED_LEADS,
    STANDARD_LAYOUT,
    PAPER_SPEED_MM_PER_S,
    GAIN_MM_PER_MV,
    SAMPLE_RATE_HZ,
    TARGET_SAMPLES,
    LEAD_DURATION_S,
)
from .grid_suppression import ImageStandardizer, PeriodicGridSuppressor
from .layout_slicer import (
    AdaptiveBandDetector,
    BandGeometryConfig,
    BandGeometryResult,
    CalibrationPulseResult,
    CalibrationVerifier,
    PerspectiveRectifyConfig,
    PerspectiveRectifier,
    derive_px_per_mm,
)
from .waveform_extractor import (
    ContinuousTraceExtractor,
    LeadCropMapper,
    LeadExtractionResult,
    TraceExtractionConfig,
)
from .pipeline import (
    digitize_ecg,
    _estimate_px_per_mm_from_dimensions,
    _extract_two_level_otsu_mask,
)

__all__ = [
    "DigitizationContract",
    "DigitizationFailure",
    "EvaluationThresholds",
    "GridDetectionConfig",
    "GridGeometry",
    "GridSuppressionResult",
    "ImageStandardizationConfig",
    "StandardizedECGImage",
    "LEAD_NAME_ALIASES",
    "LEAD_ORDER",
    "REQUIRED_LEADS",
    "STANDARD_LAYOUT",
    "PAPER_SPEED_MM_PER_S",
    "GAIN_MM_PER_MV",
    "SAMPLE_RATE_HZ",
    "TARGET_SAMPLES",
    "LEAD_DURATION_S",
    "ImageStandardizer",
    "PeriodicGridSuppressor",
    "AdaptiveBandDetector",
    "BandGeometryConfig",
    "BandGeometryResult",
    "CalibrationPulseResult",
    "CalibrationVerifier",
    "PerspectiveRectifyConfig",
    "PerspectiveRectifier",
    "derive_px_per_mm",
    "ContinuousTraceExtractor",
    "LeadCropMapper",
    "LeadExtractionResult",
    "TraceExtractionConfig",
    "digitize_ecg",
    "_estimate_px_per_mm_from_dimensions",
    "_extract_two_level_otsu_mask",
]
